### ISSUE TITLE
Error when registering commands

### ISSUE THREAD

**Issue by alexraskin** [LuisFun/discord-hono#1]
This is an awesome library! Thank you so much for your great work. 

 I am running into a small issue when trying to registar commands. 

```bash
> tsc && node register.js

node:internal/modules/cjs/loader:1078
  throw err;
  ^

Error: Cannot find module '/register.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

I followed the guide in the docs. 

Thank you!

**Comment by LuisFun** [comment]
Hi! Sorry for the late reply.

Try to make tsconfig.json the same as the [example](https://github.com/LuisFun/discord-hono-example/blob/main/package.json) for this problem.
Also add `"type": "module",` to package.json.

If that does not solve the problem, please let me know.
