### ISSUE TITLE
Subcommands?

### ISSUE THREAD

**Issue by lonelil** [LuisFun/discord-hono#2]
Is it possible to add subcommands via `new Command()` ?

**Comment by LuisFun** [comment]
You can register a subcommand with the following code
```ts
  new Command('slash', 'slash command').options(
    new SubGroupOption('group', 'group option').options(
      new SubOption('sub1', 'sub1 option').options(new Option("text", "text")),
      new SubOption('sub2', 'sub2 option'),
    ),
    new SubOption('sub3', 'sub3 option'),
  ),
```
However, the handling of the interaction side of the subcommand had not yet been implemented.
In the meantime, you can get the value of the subcommand with the following code.
```ts
  .command('slash', c => {
    console.log(c.interaction.data?.options[0]?.options[0]?.options)
    return c.res("slash cmd")
  })
```
in Discord
```
/slash group sub1 text:TEST!!
```
wrangler tail
```
 (log) [ { name: 'text', type: 3, value: 'TEST!!' } ]
```

I plan to implement it for easier handling, so please wait a little if you want to use it.

**Comment by LuisFun** [comment]
Subcommand is now easier to handle.
Please update to var.0.5.0 or higher and write your code referring to this [Docs](https://discord-hono.luis.fun/interactions/context/#get-sub).

**Comment by lonelil** [comment]
thanks!
