### ISSUE TITLE
User apps

### ISSUE THREAD

**Issue by lonelil** [LuisFun/discord-hono#3]
Would it be possible to add `integration_types` and `contexts` to the command builder to add support for user apps?

https://discord.com/developers/docs/interactions/application-commands#contexts

**Comment by lonelil** [comment]
Thank you for the update. I appreciate the effort. However, I've noticed a small issue: the 'contexts' should be a number array. Could you please look into this?

**Comment by LuisFun** [comment]
Thank you for the unnecessary hassle.
Type was corrected in ver.0.5.2.
