### ISSUE TITLE
Feature Request: Add Support for Components Custom ID with JavaScript Functions

### ISSUE THREAD

**Issue by jac00000b** [LuisFun/discord-hono#4]
**Description:**
Please add support for component custom IDs to accept a regex or a function for validation. This would allow more flexible and dynamic ID checking.

**Current Example:**
```javascript
const app = new DiscordHono()
  .component('button-1', c => c.resUpdate('Button clicked'));
```

**Proposed Enhancement:**
Allow `id` to accept regex or function:
```javascript
// Regex example
id: /fruit_([\w])+/,

// Function example
id: (id) => {
  return id.startsWith('fruit_');
},
```

**Benefits:**
- Increased flexibility in component ID validation.
- Easier handling of dynamic and complex ID patterns.

Thank you!

**Comment by luisfun** [comment]
Hi. Thank you for the request!

I’ve added support for regex (ver. 0.7.1).

---

Regarding function support, I don’t think we’ll be implementing that for now.
Instead, try the following code:

```ts
const app = new DiscordHono()
  .component('', c => c.resUpdate(c.key));

```
Although it’s not documented, specifying '' will act as a fallback if there’s no match.
Additionally, I’ve added `c.key` (ver. 0.7.1).
`c.key` contains the command name, component ID, or modal ID.

**Comment by luisfun** [comment]
Support for the regex key has been removed.
[v0.13.0](https://github.com/luisfun/discord-hono/releases/tag/v0.13.0)
