### ISSUE TITLE
Feature Request: Autocomplete Support

### ISSUE THREAD

**Issue by jac00000b** [luisfun/discord-hono#6]
I think it’d be awesome if the discord-hono package could support autocomplete for commands. It’s one of those little features that makes using bots so much smoother and faster.

Thanks!

**Comment by luisfun** [comment]
Thank you for your request!

I have a question about autocomplete, which I do not understand very well.
Command([2](https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-object-interaction-type))->Selector for autocomplete([8](https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-response-object-interaction-callback-type))->Autocomplete([4](https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-object-interaction-type))->...
Is this the full flow regarding autocomplete correct?

I wasn't sure and forgot that I had left it alone.😅

**Comment by luisfun** [comment]
I tried many things myself and was able to implement it in v0.8.3.
Documentation is [here](https://discord-hono.luis.fun/interactions/discord-hono/#autocomplete).

The behavior around Autocomplete was completely different from what I expected.

**Comment by luisfun** [comment]
Autocomplete builder was added in v0.8.4.
Documentation is [here](https://discord-hono.luis.fun/builder/autocomplete/).

Breaking change regarding autocomplete in 0.8.3->0.8.4.
