### ISSUE TITLE
How do I access Discord resources?

### ISSUE THREAD

**Issue by GoodluckH** [luisfun/discord-hono#7]
Let's say I want to get all channels and read all of the message histories. How can I do that with discord-hono? 

Do I need another lib to do that?

**Comment by luisfun** [comment]
[Get Channels](https://discord.com/developers/docs/resources/guild#get-guild-channels), [Get Messages](https://discord.com/developers/docs/resources/message#get-channel-messages)
It should be possible using these REST APIs.

Currently, discord-hono provides a [Rest Class](https://discord-hono.luis.fun/rest-api/rest/), but it's in the beta stage.

If you want to use discord-hono as the base for your bot while applying a different library for REST, [@discordjs/rest](https://discord.js.org/docs/packages/rest/main) could be a suitable option.

**Comment by GoodluckH** [comment]
Sg. Btw appreciate it for making this framework. It's exactly im looking for!
